###
# git
###

  # Change very rarely, and will cause git pull to break if it doesn't exist in this repo
- name: copy gitconfig to ~/..gitconfig/
  ansible.builtin.copy:
    src: "{{ pwd }}/files/git/gitconfig"
    dest: "{{ home }}/.gitconfig"