# .zshrc

# OSX
if [[ $(uname) == "Darwin" ]]; then
  #NOTE: Adds Homebrew commands to PATH, 'sheldon' needed shortly after
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

###
# oh-my-zsh 
###
# NOTE: This MUST come before sheldon sources oh-my-zsh
plugins=(git)

###
# Load Plugins
###
source <(sheldon source)

###
# ZSH Stuff
###
# Autoload completion scripts
autoload -Uz compinit && compinit
autoload -U promptinit; promptinit

# Set list colors for ZSH
zstyle ':completion:*' list-colors "=(#b) #([0-9]#)*=36=31"
# Disable SSH host completion
zstyle ':completion:*' hosts off

###
# Configuration
###
# NOTE: Files are loaded lexicographically by glob expansion
# Layout: 
# - 00-09: System
# - 20-29: Code
# - 30-39: Cloud
# - 50-59: Operating System
# - 80: Work
# - 99: Overrides
for configFile in $HOME/.zsh.d/*.zsh; do
  source $configFile
done

# powerlevel10k prompt
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
