
brew "fzf"
brew "z"
# Replacement for file, 'fd' binary
brew "fd"
# Replacement for grep, 'rg' binary
brew "ripgrep"
# Install common utils
brew "coreutils"
brew "htop"
brew "gpg"
brew "jq"

# Install heroku
tap "heroku/brew"
brew "heroku"

# install yarn
brew "yarn"
