# fuzzy file finder
brew "fzf"
# make cd smarter
brew "z"
# Replacement for file, 'fd' binary
brew "fd"
# Replacement for grep, 'rg' binary
brew "ripgrep"
# Install common utils
brew "coreutils"
brew "htop"
brew "gpg"
brew "jq"
brew "mtr"
brew "asciinema"

# Install heroku
tap "heroku/brew"
brew "heroku"

# install yarn
brew "yarn"
